title: Sophuckit Podcast
url: "https://princemanjee.github.io"
baseurl: "/sophuckit.github.io"

# Show all episodes regardless of date
future: true

collections:
  episodes:
    output: true
  guests:
    output: true
  hosts:
    output: true
  seasons:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "episodes"
    values:
      layout: "episode"

markdown: kramdown
# Force GitHub to NOT use any theme
remote_theme: ""
theme: ""

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package-lock.json
  - .jekyll-cache
  - .sass-cache
